version: "3"

services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - php_mvc

  php:
    build:
      context: ./.boing/docker/php
    volumes:
      - .:/srv
    networks:
      - php_mvc

  web:
    depends_on:
      - php
    build:
      context: ./.boing/docker/nginx/symfony
    volumes:
      - ./public:/srv/public
    networks:
      - php_mvc

networks:
  php_mvc:
    external: true

volumes:
  db_data:
